### PR TITLE
fixed memory leaking of custom dlg with background

### PR DESCRIPTION
**Pull request by daemon1995**

### CODE REVIEW

**Comment by RoseKavalier** [comment]
Keep looking (:

**Comment by daemon1995** [comment]
So HintBar also, i assume?

**Comment by RoseKavalier** [comment]
Now you're just guessing 🙈

**Comment by daemon1995** [comment]
well, about hintbar i was really unsure, but background is really leaking source.
was checking with H3Dlg dlg(800,600) that creates buffer for background pcx and doesn't clean that, so after it reopen dlg everytime  we have increased RAM using by several MB for each open/close.
So make it clear please, there are some more issues, right?
i mean now i got the proper debugging way - just check any member of dlg that refers to heap and check objects after calling dtor of H3Dlg obj, cause when i compared ctor/dtor and vtable address of all dlgs from H3BaseDlg to H3Dlg with idb those were lookng the right ones i believe

**Pull request closed without merging**
